-- Create questions table and seed data
-- Run after schema.sql. Usage: mysql -u root -p brainbolt < scripts/create_questions_table.sql

CREATE TABLE IF NOT EXISTS questions (
  id         INT          PRIMARY KEY,
  difficulty INT          NOT NULL,
  question   TEXT         NOT NULL,
  options    JSON         NOT NULL,
  answer     VARCHAR(5)   NOT NULL,
  INDEX idx_questions_difficulty (difficulty)
);

INSERT INTO questions (id, difficulty, question, options, answer) VALUES
(1, 1, 'What is the capital of France?', '["Berlin", "Paris", "Madrid", "Rome"]', 'B'),
(11, 1, 'What is the largest ocean on Earth?', '["Atlantic", "Indian", "Arctic", "Pacific"]', 'D'),
(12, 1, 'How many continents are there?', '["5", "6", "7", "8"]', 'C'),
(13, 1, 'What is the capital of Japan?', '["Seoul", "Beijing", "Tokyo", "Bangkok"]', 'C'),
(14, 1, 'Which country is known as the Land of the Rising Sun?', '["China", "Japan", "Korea", "Thailand"]', 'B'),
(2, 2, 'Which planet is known as the Red Planet?', '["Earth", "Venus", "Mars", "Jupiter"]', 'C'),
(15, 2, 'What is the chemical symbol for water?', '["H2O", "CO2", "O2", "NaCl"]', 'A'),
(16, 2, 'How many legs does a spider have?', '["6", "8", "10", "12"]', 'B'),
(17, 2, 'What is the closest star to Earth?', '["Proxima Centauri", "Sirius", "The Sun", "Alpha Centauri"]', 'C'),
(18, 2, 'What gas do plants absorb from the atmosphere?', '["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"]', 'C'),
(3, 3, 'What is 15 multiplied by 4?', '["50", "60", "70", "80"]', 'B'),
(19, 3, 'What is 25 divided by 5?', '["3", "4", "5", "6"]', 'C'),
(20, 3, 'What is 12 + 18?', '["28", "30", "32", "34"]', 'B'),
(21, 3, 'What is 100 minus 37?', '["61", "63", "65", "67"]', 'B'),
(22, 3, 'What is 7 times 8?', '["54", "56", "58", "60"]', 'B'),
(4, 4, 'Which element has the chemical symbol ''O''?', '["Gold", "Silver", "Oxygen", "Iron"]', 'C'),
(23, 4, 'What is the chemical symbol for gold?', '["Go", "Gd", "Au", "Ag"]', 'C'),
(24, 4, 'What is the hardest natural substance on Earth?', '["Gold", "Iron", "Diamond", "Platinum"]', 'C'),
(25, 4, 'What is the most abundant gas in Earth''s atmosphere?', '["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"]', 'C'),
(26, 4, 'What is the freezing point of water in Celsius?', '["-10°C", "0°C", "10°C", "32°C"]', 'B'),
(5, 5, 'Who painted the Mona Lisa?', '["Van Gogh", "Picasso", "Da Vinci", "Monet"]', 'C'),
(27, 5, 'In which year did World War II end?', '["1943", "1944", "1945", "1946"]', 'C'),
(28, 5, 'Who wrote ''Romeo and Juliet''?', '["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"]', 'B'),
(29, 5, 'What is the name of the famous tower in Paris?', '["Big Ben", "Eiffel Tower", "Leaning Tower", "Statue of Liberty"]', 'B'),
(30, 5, 'Which ancient wonder was located in Alexandria?', '["Hanging Gardens", "Colossus", "Lighthouse", "Pyramids"]', 'C'),
(6, 6, 'What is the square root of 144?', '["10", "11", "12", "14"]', 'C'),
(31, 6, 'What is 15% of 200?', '["25", "30", "35", "40"]', 'B'),
(32, 6, 'What is the value of π (pi) to two decimal places?', '["3.12", "3.14", "3.16", "3.18"]', 'B'),
(33, 6, 'What is 2 to the power of 5?', '["16", "32", "64", "128"]', 'B'),
(34, 6, 'What is the area of a circle with radius 5? (π ≈ 3.14)', '["78.5", "31.4", "15.7", "62.8"]', 'A'),
(7, 7, 'Which continent is the Sahara Desert located in?', '["Asia", "Africa", "South America", "Australia"]', 'B'),
(35, 7, 'What is the longest river in the world?', '["Amazon", "Nile", "Yangtze", "Mississippi"]', 'B'),
(36, 7, 'Which country is home to the Great Barrier Reef?', '["New Zealand", "Australia", "Indonesia", "Philippines"]', 'B'),
(37, 7, 'What is the smallest country in the world?', '["Monaco", "Vatican City", "San Marino", "Liechtenstein"]', 'B'),
(38, 7, 'Which mountain range separates Europe from Asia?', '["Alps", "Himalayas", "Ural Mountains", "Andes"]', 'C'),
(8, 8, 'In what year did the Titanic sink?', '["1905", "1912", "1918", "1922"]', 'B'),
(39, 8, 'Who was the first person to walk on the moon?', '["Buzz Aldrin", "Neil Armstrong", "Michael Collins", "John Glenn"]', 'B'),
(40, 8, 'In which year did the Berlin Wall fall?', '["1987", "1989", "1991", "1993"]', 'B'),
(41, 8, 'Who was the first President of the United States?', '["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"]', 'C'),
(42, 8, 'In which year did World War I begin?', '["1912", "1914", "1916", "1918"]', 'B'),
(9, 9, 'What is the largest organ in the human body?', '["Heart", "Liver", "Skin", "Lungs"]', 'C'),
(43, 9, 'How many chambers does the human heart have?', '["2", "3", "4", "5"]', 'C'),
(44, 9, 'What is the powerhouse of the cell?', '["Nucleus", "Mitochondria", "Ribosome", "Golgi Apparatus"]', 'B'),
(45, 9, 'How many bones are in an adult human body?', '["196", "206", "216", "226"]', 'B'),
(46, 9, 'What is the scientific name for the human species?', '["Homo erectus", "Homo sapiens", "Homo habilis", "Homo neanderthalensis"]', 'B'),
(10, 10, 'Which physicist developed the theory of General Relativity?', '["Newton", "Bohr", "Einstein", "Hawking"]', 'C'),
(47, 10, 'What is the speed of light in vacuum (approximately)?', '["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"]', 'A'),
(48, 10, 'What is the smallest unit of matter?', '["Molecule", "Atom", "Electron", "Quark"]', 'B'),
(49, 10, 'Who discovered the law of gravity?', '["Galileo", "Newton", "Einstein", "Kepler"]', 'B'),
(50, 10, 'What is the formula for energy (Einstein''s equation)?', '["E = mc", "E = mc²", "E = mv²", "E = mgh"]', 'B');
